import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AIChat from "@/components/AIChat";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { CartProvider } from "@/lib/CartContext";

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        <CartProvider>
          {children}
        </CartProvider>
        <AIChat />
        <Toaster richColors position="top-right" />
      </body>
    </html>
  );
}
